services:

#  mcp-gateway:
#    image: docker/mcp-gateway:latest
#    ports:
#      - 9011:9011
#    volumes:
#      - "/var/run/docker.sock:/var/run/docker.sock"
#      - "/run/host-services/backend.sock:/run/host-services/backend.sock"
#    command:
#      - --verbose
#      - --transport=sse
#      - --secrets=docker-desktop:/run/secrets/mcp_secret
#      - --servers=brave,wikipedia-mcp,puppeteer,github,openbnb-airbnb,google-maps
#      - --tools=openbnb-airbnb:*
#      - --tools=brave_web_search
#      - --tools=wikipedia-mcp:*
#      - --tools=github:add_issue_comment
#      - --tools=github:create_issue
#      - --tools=github:list_issues
#      - --tools=github:get_issue
#      - --tools=github:list_pull_requests
#      - --tools=github:get_pull_request
#      - --tools=puppeteer:*
#      - --tools=google-maps:*
#      - --port=9011
#    secrets:
#      - mcp_secret

  zipkin:
    image: 'openzipkin/zipkin:latest'
    ports:
      - "9411:9411"

  agent:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - DOCKER_MCP=http://mcp-gateway:9011
      - BRAVE_API_KEY=${BRAVE_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      #- SPRING_PROFILES_ACTIVE=starwars,neo,docker-desktop,docker,shell
    depends_on:
      - mcp-gateway
      - zipkin
    profiles:
      - in-docker

secrets:
  mcp_secret:
    file: ./.mcp.env

