server:
  port: 8747

spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
      # additional-paths: src/main/resources/templates
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
  web:
    resources:
      cache:
        period: 0
      chain:
        cache: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: email,profile
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'

embabel:
  security:
    enabled: false

  # Add additional MCP tools
  agent:
    platform:
      tools:
        includes:
          weather:
            description: Get the current weather and forecast for any location
            provider: Docker
            tools:
              - weather

  tripper:
    word-count: 1200
    image-width: 850
    max-concurrency: 1

    # Anthropic models will give better results but are more expensive
    thinker-llm:
      model: gpt-4.1

    researcher:
      persona:
        role: Researcher
        goal: Research points of interest for a travel plan
        backstory: >
          You are an expert researcher who can find interesting stories about art, culture, 
          and famous people associated with places
      llm:
        model: gpt-4.1-mini


    planner:
      persona:
        name: Hermes
        persona: You are an expert travel planner
        voice: friendly and concise
        objective: Help the user plan an amazing trip, considering their requirements and preferences
      llm:
        model: gpt-4.1


logging:
  pattern:
    console: '%clr(%d{HH:mm:ss.SSS}){faint} %clr([%t]){magenta} %clr(%-5level) %clr(%logger{0}){cyan} %clr(-){faint} %msg%n'
  level:
    com.embabel.agent.core.ActionRunner: DEBUG
    com.embabel.agent.config.models.DockerLocalModels: DEBUG
    com.embabel.agent.web.sse.SSEController: INFO
    com.embabel.agent.tools.mcp: DEBUG
#    com.embabel.agent: DEBUG
    io.modelcontextprotocol.client.transport.StdioClientTransport: WARN
